openapi: 3.0.1
info:
  version: 1.0.0
  title: Web API docs
  description: team 17 API 문서입니다
  license:
    name: MIT
servers:
  - url: 'http://localhost:5000/'
tags:
  - name: user
  - description: User API 입니다.
  - name: recommend
  - description: User가 추천받은 영양제 정보 API 입니다.
  - name: schedule
  - description: User 영양제 스케줄 및 생체리듬 관리 API 입니다.
paths:
  /user/register:
    post:
      tags:
        - user
      summary: 회원가입 API 입니다.
      description: '(필수) user_name, email, password (선택) gender, age_range, job'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          $ref: '#/components/responses/successResponse'
  /user/login:
    post:
      tags:
        - user
      summary: 로그인 API 입니다.
      description: '(필수) email, password'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
      responses:
        '200':
          $ref: '#/components/responses/successResponse'
  /user/updateInfo:
    put:
      tags:
        - user
      summary: 회원 정보 수정 API 입니다.
      description: '(필수) accessToken (선택) gender, age_range, job'
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                gender:
                  type: string
                age_range:
                  type: string
                job:
                  type: string
      responses:
        '200':
          $ref: '#/components/responses/successResponse'
        '400':
          description: accessToken이 유효하지 않습니다.
  /user/withdrawal:
    delete:
      tags:
        - user
      summary: 회원 탈퇴 API 입니다.
      description: (필수) accessToken
      security:
        - bearerAuth: []
      responses:
        '200':
          $ref: '#/components/responses/successResponse'
  /schedule:
    get:
      tags:
        - schedule
      summary: 전체 스케줄 조회 API 입니다.
      description: '(필수) accessToken, start, finish'
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: start
          schema:
            type: string
          description: GET /schedule?start='2020-02-01'&finish='2020-02-01'
        - in: query
          name: finish
          schema:
            type: string
          description: GET /schedule?start='2020-02-01'&finish='2020-02-01'
      responses:
        '200':
          $ref: '#/components/responses/successResponse'
        '400':
          description: accessToken이 유효하지 않습니다.
  /schedule/create:
    post:
      tags:
        - schedule
      summary: 영양제 / 생체리듬 스케줄 생성 API 입니다.
      description: '(필수) accessToken, type, start, finish, to_do'
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                type: string
                start:
                  type: string
                  format: date_time
                finish:
                  type: string
                  format: date_time
                to_do:
                  type: string
      responses:
        '200':
          $ref: '#/components/responses/successResponse'
        '400':
          description: accessToken이 유효하지 않습니다.
  /schedule/daily-supplement:
    post:
      tags:
        - schedule
      summary: '아침, 점심, 저녁 영양제 저장 API 입니다.'
      description: '(필수) accessToken, type, fk_supplement_id'
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                type: string
                fk_supplement_id:
                  type: string
      responses:
        '200':
          $ref: '#/components/responses/successResponse'
        '400':
          description: accessToken이 유효하지 않습니다.
  /checklist/create:
    post:
      tags:
        - schedule
      summary: 체크리스트 생성 API 입니다.
      description: '(필수) accessToken, date, one, two, three, four, five, six'
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                date:
                  type: string
                  format: date
                one:
                  type: boolean
                two:
                  type: boolean
                three:
                  type: boolean
                four:
                  type: boolean
                five:
                  type: boolean
                six:
                  type: boolean
      responses:
        '200':
          $ref: '#/components/responses/successResponse'
        '400':
          description: accessToken이 유효하지 않습니다.
components:
  schemas:
    User:
      type: object
      required:
        - user_name
        - email
        - password
      properties:
        user_name:
          type: string
        email:
          type: string
          format: email
        password:
          type: string
        gender:
          type: string
          enum:
            - M
            - F
        age_range:
          type: string
        job:
          type: string
    Error:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
  responses:
    successResponse:
      description: successful request
      content:
        application/json:
          schema:
            type: object
            properties: null
    BadRequest:
      description: bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    InternalServerError:
      description: server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
